# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8845c7f9f7483f40f201f0d9a12a74581d349aa958496443ae439c5d0b32360ddcb6dca387acd19efc8507752bff6ea7a686b2a0e2b6acb9a9d42ee66e360672

test:
  secret_key_base: 5f39cbfcd4440d874d661727b65131b15bd86956555d55f2d4def95fbf8ae81ffd64963ee127af145f6244856a4ef5a037ed9cce3339b7e0eba6574496adbdb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
